# Generated by Django 4.0.4 on 2022-04-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50)),
                ('stock', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
